global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'ec2_discovery'
    relabel_configs:
      - source_labels: [ __meta_ec2_tag_Name ]
        target_label: job
    ec2_sd_configs:
      - port: 9100
        region: us-east-1
        profile: instance_profile-infra

      - port: 14269
        region: us-east-1
        profile: instance_profile-infra
        filters:
          - name: tag:Name
            values:
              - jaeger-server

      - port: 9101
        region: us-east-1
        profile: instance_profile-infra
        filters:
          - name: tag:Name
            values:
              - load_tests