global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'ec2_discovery_node_exporter'
    scrape_interval: 15s
    ec2_sd_configs:
      - port: 9100
        region: us-east-1
        profile: instance_profile-infra

  - job_name:  'static'
    scrape_interval: 15s

    static_configs:
      - targets:
          # jaeger server
          - '10.0.1.33:14269'
          # load tests
          - '10.0.1.124:9101'