global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'ec2_discovery_node_exporter'
    scrape_interval: 15s
    ec2_sd_configs:
      - port: 9100
        region: us-east-1
        profile: instance_profile-infra
#    relabel_configs:
#      - source_labels: [__meta_ec2_tag_monitoring_status]
#        regex: .*monitored_node.*
#        action: keep
#      - source_labels: [__meta_ec2_tag_Name]
#        target_label: group

  - job_name:  'static'
    scrape_interval: 15s

    static_configs:
      - targets:
#          jaeger server
          - '3.215.180.186:14250'